### ISSUE TITLE
Create a tag

### ISSUE THREAD

**Issue by filmkorn** [jedypod/nuke-colortools#1]
Hello,

If you don't mind, could you create a tag to help us version this package on our end?

Best,

Mitja

**Comment by jedypod** [comment]
Hey Mitja! 
Sorry I totally missed this. 

I created [a tag for v0.0.1](https://github.com/jedypod/nuke-colortools/releases/tag/v0.0.1).

Although it's been so long you've probably figured out a workaround by now!
