### ISSUE TITLE
"nuke-colortools.toolsets.visualize.HueSweep" has a dark line in the blue channel.

### ISSUE THREAD

**Issue by KelSolaar** [jedypod/nuke-colortools#2]
![image](https://user-images.githubusercontent.com/99779/117586722-03035100-b16e-11eb-8ddb-da9c0314faf6.png)

In `Expression10`:

```tcl
x>width/3&&x<width/3*2
```

should be 

```tcl
x>width/3&&x<=width/3*2
             ^
```

**Comment by jedypod** [comment]
Sorry totally missed this! Thanks for the fix, I've merged it.
