### ISSUE TITLE
PlotChromaticity

### ISSUE THREAD

**Issue by antonmeleshkevich** [jedypod/nuke-colortools#7]
Hi, Jed!
Macbeth colorchecker colors reference dots in _PlotChromaticity.nk_ don't match the colors from _MacbethColorchecker.nk_ and _ColorChecker24Sweep.nk_. Looks like its a white point mismatch.
(Or I use it wrong)

**Comment by jedypod** [comment]
Thanks @antonmeleshkevich ! You are indeed correct, there was a missing CAT transform. I've pushed a fix https://github.com/jedypod/nuke-colortools/commit/370e32e9ad8dbc27c84570037888b9afb4492730

Thanks for flagging it!

**Comment by antonmeleshkevich** [comment]
@jedypod Looks like it's only fixed for Gamuts with D65 white point, but not for AP1 and AP0. ACEScg and ACES are still off.
